# Generated by Django 5.0.4 on 2024-05-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.productcatagory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date_product',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
