# Generated by Django 5.0.4 on 2024-05-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_catagory_product_date_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productcatagory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
