# Generated by Django 5.0.6 on 2024-06-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCatagory',
            new_name='ProductCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
