name: Deploy to cPanel

on:
  push:
    branches: [ main ]  # You can change "main" to your desired branch

jobs:
    web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest  # You can choose a different runner OS if needed
    steps:
      - uses: actions/checkout@v3  # Checks out your code from GitHub
        with:
          fetch-depth: 2

      - name:  Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir:  ${{ env.LOCAL_DIRECTORY }} # Replace with your directory
          server-dir: /home/pfulhebk/repositories/PiringTerbang/backend  # Replace with your cPanel directory
